# Generated by Django 5.2.4 on 2025-07-20 17:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gluten_free', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter'), ('unit', 'Unit'), ('kg', 'Kilogram'), ('l', 'Liter')], default='unit', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('donut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.donut')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='donut',
            name='ingredients',
            field=models.ManyToManyField(related_name='donuts', through='donuts.Recipe', to='donuts.ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(fields=('donut', 'ingredient'), name='unique_donut_ingredient'),
        ),
    ]
