# Generated by Django 5.2.4 on 2025-07-27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0002_customer_employee_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.BigIntegerField(unique=True)),
                ('timestamp', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DonutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('donut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.donut')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donuts.order')),
            ],
        ),
    ]